### ISSUE TITLE
Is the extension finished or functional?

### ISSUE THREAD

**Issue by SantiFerre** [YoYoGames/GMEXT-InAppUpdate#1]
### Description

I'm trying to implement the extension in my project, but when I call the request info function `inappupdate_request_info()`, it always returns success = 0.

On the other hand, I don't think the documentation is finished either, so it is difficult for me to know if I am making a mistake in trying to implement the extension.

Thank you in advance.

### Steps To Reproduce

1. Start GameMaker
2. Import the extension
3. Call inappupdate_request_info();
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

Monthly

### Which platform(s) are you seeing the problem on?

Android

### Compiler Log File

- [ ] I have attached my compiler log in a text file

### Sample .yyz File

- [ ] I have attached a small sample project

**Comment by DiasFranciscoA** [comment]
Hello @SantiFerre,

Thank you for reaching out to us. Yes the extension is finished and functional at this point. This is NOT something that you can use from the IDE it will only work once your game is published. I will mark @jzavala-YYG here so he gives this a look once he is able to.

> [!NOTE]
> Currently, our approach is to initially release extensions on GitHub with basic technical documentation. This initial set includes details on available functions, their signatures, constants, and asynchronous events. This approach allows users to start integrating and experimenting with the extension immediately.
>
>It's important to note that during this early access phase, end users may need to engage in some exploratory work to fully understand how the extension operates. This hands-on experience can be invaluable, although we recognize it requires additional effort.
>
>Following this initial phase, the extension is placed in the queue for our Technical Documentation team, who will enhance the documentation with further details and practical examples. This comprehensive documentation aims to facilitate a deeper and more intuitive use of the extension.

We appreciate your patience as we balance the timely release of new extensions, which are crucial for studios and teams, with the thorough preparation of detailed documentation.

**Comment by SantiFerre** [comment]
Hello @DiasFranciscoA,

I apologize for the inconvenience, but you were right. I have tested the extension again in the internal testing channel on the Google Play Console, and it is 100% functional. It seems that last time I tested it, there was enough time for the test version to be uploaded, and I mistakenly thought it wasn't working properly.

Thank you very much for everything.
